### ISSUE TITLE
PHP 7 deprecated style constructors

### ISSUE THREAD

**Issue by georgearnall** [anderly/woocommerce-mailchimp#14]
Just noticed a warning stating:

_PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; MCAPI has a deprecated constructor in ..woocommerce-mailchimp/classes/api/class-MCAPI.php on line 3_

More Information:
[PHP Docs](http://php.net/manual/fr/migration70.deprecated.php#migration70.deprecated.php4-constructors)

Should be pretty straight forward to sort out.

**Comment by anderly** [comment]
This will be fixed in upcoming release as part of move to MailChimp API v3.
