### ISSUE TITLE
Hiya, could someone please help me with this issue on my wordpress website, I installed mailchimp pluggins and this error is coming up on my screen, I tried to deactivate it and delete mailchimp but it still present . Warning: Invalid argument supplied for foreach() in /home/swapyou0/public_html/iron4me.com/wp-content/plugins/mailchimp-subscribe-sm/admin/classes/admin.php on line 542

### ISSUE THREAD

**Issue by corinamour** [anderly/woocommerce-mailchimp#22]
Warning: Invalid argument supplied for foreach() in /home/swapyou0/public_html/iron4me.com/wp-content/plugins/mailchimp-subscribe-sm/admin/classes/admin.php on line 542.

The website i need help with is www.iron4me.com.

I will appreciate any help from you guys.

Thanks in advance

**Comment by anderly** [comment]
Based on the filepath, it looks like you’re using a plugin called mailchimp-subscribe-sm. Our plugin is called WooCommerce MailChimp and gets installed in a directory named woocommerce-mailchimp.

**Comment by anderly** [comment]
Closing as this references a plugin other than WooCommerce Mailchimp.
