### ISSUE TITLE
Not all lists are selectable

### ISSUE THREAD

**Issue by foxglove666** [anderly/woocommerce-mailchimp#23]
I have been using this plugin for a while now and I have a multisite setup with each site using its own group in one list.

I have created a new group on Mailchimp but this is not on the group's list in the woocommerce settings page. I have added a test user to the list and still, this is not listed. I have also waited for over a week in case it was a slow sync issue but still this is now shown. Can someone have a look at this for me, please. 

![image](https://user-images.githubusercontent.com/12566415/40623564-65f2b07e-629f-11e8-9c6e-942f3577a959.png)
![image](https://user-images.githubusercontent.com/12566415/40623588-8a800572-629f-11e8-957c-26cd732237bd.png)

**Comment by anderly** [comment]
@foxglove666,

Thanks for reporting this issue. It could be a paging issue when we retrieve the lists from MailChimp. Just curious, how many lists do you have in the referenced MailChimp account?

**Comment by foxglove666** [comment]
@anderly 

I have 12 groups in that list.

**Comment by anderly** [comment]
@foxglove666 this should be fixed as we set the count parameter for the api to 100 for list retrieval. Can you confirm if you're still seeing this issue?

**Comment by anderly** [comment]
Closing as this has been fixed.
