### ISSUE TITLE
Ability to put links into the opt in label

### ISSUE THREAD

**Issue by DanielJanke** [anderly/woocommerce-mailchimp#24]
Hey,

In Germany we need the function that we have the link for the data protection declaration directly in the opt-in label.

**Comment by anderly** [comment]
Hi @DanielJanke,

This is currently achievable through overriding the action_hook `ss_wc_mailchimp_opt_in_checkbox`.

Also, see this post regarding additional options: https://wordpress.org/support/topic/gdpr-and-mailchimp/

We are looking into the possibility of supporting HTML/links in the opt-in label in a future update.

**Comment by DanielJanke** [comment]
Thank you for your fast feedback! 😄
