### ISSUE TITLE
Is the plugin also add a product name as  tag on mailchimp subscriber?

### ISSUE THREAD

**Issue by codetycon** [anderly/woocommerce-mailchimp#25]
Is the plugin also add a product name or category name as tag on MailChimp subscriber?

**Comment by anderly** [comment]
@codetycon sorry for the delay in responding. Our pro version (https://www.saintsystems.com/products/woocommerce-mailchimp-pro/) will support adding tags based on products purchased in the next release.

**Comment by anderly** [comment]
Yesterday we released v2.3.0 with tag support in our free version and our [pro version](https://www.saintsystems.com/products/woocommerce-mailchimp-pro/) now supports tagging subscribers based on individual products purchased. Read more on our blog [here](https://www.saintsystems.com/blog/woocommerce-mailchimp-pro-2-3-0-released-tag-support/).
