### ISSUE TITLE
Bug found in get_interest_categories_with_interests function

### ISSUE THREAD

**Issue by anderly** [anderly/woocommerce-mailchimp#29]
Copied from support post [here](https://wordpress.org/support/topic/bug-found-in-get_interest_categories_with_interests-function/).

The public function get_interest_categories_with_interests (class-ss-wc-mailchimp.php:404) incorrectly returns false if ANY of the categories has no interests.

The expected behavior would be to return false if the final results array had only categories with no interests (or better yet, just don’t add categories without interests to the results array).

The end result/problem for the user can be seen in the plugin settings page, in the “Interest Groups” field, which incorrectly returns “This list does not have interest groups enabled”.

**Comment by dustysheldon** [comment]
Just to add, commenting out `return false` in the class-ss-wc-mailchimp.php:418-420 conditional resolves the issue for testing purposes:

`if ( ! $interests ) {
    // return false;
}`

**Comment by anderly** [comment]
@dustysheldon,

Just looking at this again and I'm thinking the `return false` [here](https://github.com/anderly/woocommerce-mailchimp/blob/6abce3db0b4be6a848cba0a2d561de35db82b120/includes/class-ss-wc-mailchimp.php#L419) should instead be `continue` so that it continues through the for loop without bailing.

That would achieve what you mentioned where it would exclude categories with no interests, while still returning categories with interests.

Let me know what you think.

**Comment by anderly** [comment]
Closed by 47aab92
