### ISSUE TITLE
transient key length

### ISSUE THREAD

**Issue by ctalkington** [anderly/woocommerce-mailchimp#7]
I noticed that a site was constantly slow and tracked it down to trying to use the MC API every admin load.

Your stored transient ss_wc_mailchimp_list_{md5:32} (53 long) with expiry is invalid because:

> The key of a transient that doesn’t expire has a maximum length of 53 characters. The key of a transient that does expire has a maximum length of 45 characters. Please note the difference between the two because when you attempt to set an expiring transient with a key length between 46 and 53 characters, the transient will store but will be deleted before it can be returned by get_transient due to the missing _transient_timeout_ option.
http://www.barrykooij.com/maximum-option-transient-key-length/

**Comment by anderly** [comment]
Sorry for the delay in getting to this. I've shortened the transient key and just pushed version 1.3.3 with this change. Please check it out and let me know if you see an improvement.
